image: itsplus/s2shape-test-harness

stages:
  - build
  - test

services:
  - mongo

variables:
  MONGO_HOST: mongo

before_script:
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet build
    - cd MongoDbDataLoader
    - dotnet run
    - cd ..
    - dotnet test
    - cd MongoDbSupplyCollectorTests/bin/Debug/netcoreapp2.2/
    - SupplyCollectorTestHarness
