image: s2shape/s2shape-test-harness:latest

stages:
  - build
  - test

services:
  - mongo

variables:
  MONGO_HOST: mongo
  MONGO_DB: s2

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/MongoDbSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init MongoDbSupplyCollector mongodb://$MONGO_HOST/$MONGO_DB
    - dotnet SupplyCollectorDataLoader.dll -xunit MongoDbSupplyCollector mongodb://$MONGO_HOST/$MONGO_DB
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test
  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/MongoDbSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init MongoDbSupplyCollector mongodb://$MONGO_HOST/$MONGO_DB
    - dotnet SupplyCollectorDataLoader.dll -xunit MongoDbSupplyCollector mongodb://$MONGO_HOST/$MONGO_DB
    - dotnet SupplyCollectorDataLoader.dll -samples MongoDbSupplyCollector mongodb://$MONGO_HOST/$MONGO_DB TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/MongoDbSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness
