image: microsoft/dotnet:latest

stages:
  - build
  - test

services:
  - mongo

before_script:
  - dotnet restore

build:
  stage: build
  script:
    - dotnet build
    - cd MongoDbDataLoader && dotnet run

test:
  stage: test
  script:
    - dotnet test